### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by unieagle** [killbill/killbill-client-ruby#20]
Hi, do you have any document to describe how to use this client? Thanks!

**Comment by pierre** [comment]
I have added the basic examples from the [Getting Started](http://docs.killbill.io/0.16/getting_started.html#_ruby_2) guide in the [README](https://github.com/killbill/killbill-client-ruby/blob/master/README.md). Additionally, our integration tests have lots of [examples](https://github.com/killbill/killbill-integration-tests).

If you have further questions, feel free to reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users).

**Comment by unieagle** [comment]
Cool, thank you very much!
