### ISSUE TITLE
remove_custom_field method doesn't work properly

### ISSUE THREAD

**Issue by kmanuk** [killbill/killbill-client-ruby#78]
`remove_custom_field` method deletes all custom_fields of model from which it actually called. There is parameter `customFieldList`, which should be `customField`, as in api of killbill [link](https://killbill.github.io/slate/#account-remove-custom-fields-from-account) . The tests passed because the edge case is not covered if the user would like to try to [remove one custom field. ](url)

**Comment by pierre** [comment]
Thanks for the report! Indeed, the API was changed in 0.20.x but it looks like the client hadn't been updated: https://github.com/killbill/killbill/commit/ad878be4fa078ec27cae4736da1fa20d5c02ae88#diff-0fe9bc9412a2d73ca1aa2ba57c084b9cf782d6846dd21f5c589032c40bcfbd46
