### ISSUE TITLE
Write missing Ruby code

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-client-ruby#88]
Ruby code is missing for the following methods:

- [x] [Tenant push notifications](https://killbill.github.io/slate/?ruby#tenant-push-notifications)
- [x] [Tenant System properties configuration](https://killbill.github.io/slate/?ruby#tenant-system-properties-configuration)
- [x] [Tenant Payment States Machine configuration](https://killbill.github.io/slate/?ruby#tenant-payment-state-machines)
- [x] [Update Subscription Quantity](https://killbill.github.io/slate/?ruby#subscription-update-the-subscription-quantity)
- [x] [Retrieve Paginated Invoices](https://killbill.github.io/slate/?shell#account-retrieve-paginated-account-invoices)
- [x] [Retrieve Paginated Bundles](https://killbill.github.io/slate/?shell#bundle-list-bundles)
- [x] [Retrieve account timeline](https://killbill.github.io/slate/#account-retrieve-account-timeline)
- [x] [Retrieve subscription audit logs with history](https://killbill.github.io/slate/?ruby#subscription-retrieve-subscription-audit-logs-with-history-by-subscription-id)
- [x] [Retrieve subscription event audit logs with history](https://killbill.github.io/slate/?ruby#subscription-retrieve-subscription-event-audit-logs-with-history-by-subscription-event-id)
- [x] [Retrive payment method audit logs with history](https://killbill.github.io/slate/?ruby#payment-method-retrieve-payment-method-audit-logs-with-history-by-id)
- [x] [Mark a pending payment transaction as succeeded or failed
](https://killbill.github.io/slate/payment-transaction.html#mark-a-pending-payment-transaction-as-succeeded-or-failed)
- [x] [Trigger Invoice Group Run](https://killbill.github.io/slate/invoice.html#trigger-an-invoice-group-run)
- [x] [Retrieve Invoice Group](https://killbill.github.io/slate/invoice.html#retrieve-an-invoice-group)
- [x] [Retrieve Invoice Payments](https://killbill.github.io/slate/invoice.html#retrieve-payments-associated-with-an-invoice)

This code needs to be added and the docs need to be updated.

**Comment by KBbitsP** [comment]
* I believe the equivalent function for getting bundles paginated and invoices paginated are missing. 

paginated invoices : https://killbill.github.io/slate/?shell#account-retrieve-paginated-account-invoices

paginated bundles : https://killbill.github.io/slate/?shell#bundle-list-bundles

**Comment by KBbitsP** [comment]
- [ ] [Modify Custom fields for an account ](https://killbill.github.io/slate/#account-modify-custom-fields-for-an-account)

**Comment by KBbitsP** [comment]
- [ ] [Validate a catalog XML](https://killbill.github.io/slate/catalog.html#validate-a-catalog-xml)

**Comment by tungleduyxyz** [comment]
Won't fix:
- Retrieve account timeline: Code existed
- Retrieve payment method audit logs with history: Code existed
