### ISSUE TITLE
Fix incorrect ruby code

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-client-ruby#89]
The Ruby code is incorrect for the following methods:

- [x] [Delete subscription custom fields](https://killbill.github.io/slate/?ruby#subscription-remove-custom-fields-from-subscription) - The API endpoint allows deleting multiple custom fields when multiple `customField` query parameters are specified. Refer to the **Query Parameters** section. However, the Ruby code only allows specifying a single custom field. So, the Ruby code needs to be updated so it can accept multiple `customField` values and pass these to the server side.
- [x] [Add Subscription Custom Fields](https://killbill.github.io/slate/subscription.html#add-custom-fields-to-subscription) - This API endpoint allows adding multiple custom fields to a subscription at once. However, the Ruby code only allows specifying a single custom field and needs to be updated
- [x] - [Modify subscription custom fields](https://killbill.github.io/slate/subscription.html#modify-custom-fields-for-a-subscription) - This API endpoint allows modifying multiple custom fields at once. However, the Ruby code only allows specifying a single custom field and needs to be updated
- [x] [Add Subscription Tags](https://killbill.github.io/slate/?ruby#subscription-add-tags-to-subscription) - This API endpoint allows adding multiple tags to a subscription at once. However, the Ruby code only allows specifying a single tag and needs to be updated
- [x] [Delete Subscription Tags](https://killbill.github.io/slate/?ruby#subscription-remove-tags-from-subscription) - This API endpoint allows deleting multiple tags from a subscription at once. However, the Ruby code only allows specifying a single tag and needs to be updated
- [x] [Payment methods custom fields section](https://killbill.github.io/slate/?ruby#payment-method-custom-fields) - None of the code snippets in this section work. They cause a ` undefined method` error. I think this is because [payment_method.rb](https://github.com/killbill/killbill-client-ruby/blob/master/lib/killbill_client/models/payment_method.rb) does not include `CustomFieldHelper` as done in [subscription.rb](https://github.com/killbill/killbill-client-ruby/blob/0c897c2006f5a8e22bbc98176e91200ff02253cd/lib/killbill_client/models/subscription.rb#L6C38-L6C55). 
- [x] [Add Payment Method Custom Field](https://killbill.github.io/slate/?ruby#payment-method-add-custom-fields-to-a-payment-method) and [Delete Payment Method Custom Field](https://killbill.github.io/slate/?ruby#payment-method-remove-custom-fields-from-payment-method) - These endpoints need to be updated to allow creating/deleting multiple custom fields
- [x] The [Retrieve Subscription by Id](https://killbill.github.io/slate/subscription.html#retrieve-a-subscription-by-id) accepts a `AUDIT` but this is not present in the Ruby code and needs to be added.
- [x]  The [Retrieve Subscription by Key](https://killbill.github.io/slate/subscription.html#retrieve-a-subscription-by-key) accepts a `AUDIT` query parameter but this is not present in the Ruby code and needs to be added.
- [x] The [Retrieve Payment Method by Id](https://killbill.github.io/slate/payment-method.html#retrieve-a-payment-method-by-id) accepts an `AUDIT` query parameter/ `pluginProperties` query parameter but this is not present in the Ruby code and needs to be added.
- [x] The [Retrieve Payment Method by Key](https://killbill.github.io/slate/payment-method.html#retrieve-a-payment-method-by-external-key) accepts an `AUDIT` / `pluginProperties` query parameter but this is not present in the Ruby code and needs to be added.
- [x] The [Retrieve Payment by Transaction Id](https://killbill.github.io/slate/payment-transaction.html#retrieve-a-payment-by-transaction-id) accepts an `AUDIT` / `pluginProperties` query parameter but this is not present in the Ruby code and needs to be added.
- [x] The [Retrieve Payment by Transaction Key](https://killbill.github.io/slate/payment-transaction.html#retrieve-a-payment-transaction-by-external-key) accepts an `AUDIT` / `pluginProperties` query parameter but this is not present in the Ruby code and needs to be added.
- [x] [Payment transaction custom fields section](https://killbill.github.io/slate/payment-transaction.html#custom-fields) - None of the code snippets in this section work. They cause a ` undefined method` error. I think this is because [transaction.rb](https://github.com/killbill/killbill-client-ruby/blob/0c897c2006f5a8e22bbc98176e91200ff02253cd/lib/killbill_client/models/transaction.rb) does not include `CustomFieldHelper` as done in [subscription.rb](https://github.com/killbill/killbill-client-ruby/blob/0c897c2006f5a8e22bbc98176e91200ff02253cd/lib/killbill_client/models/subscription.rb#L6C38-L6C55). 
- [x] - [Payment transaction tags section](https://killbill.github.io/slate/payment-transaction.html#tags) - None of the code snippets in this section work. They cause an ` undefined method` error. I think this is because [transaction.rb](https://github.com/killbill/killbill-client-ruby/blob/0c897c2006f5a8e22bbc98176e91200ff02253cd/lib/killbill_client/models/transaction.rb) does not include `TagHelper` as done in [subscription.rb](https://github.com/killbill/killbill-client-ruby/blob/0c897c2006f5a8e22bbc98176e91200ff02253cd/lib/killbill_client/models/subscription.rb#L5C38-L5C47). 
- [x] [Trigger an invoice generation for all parked accounts](https://killbill.github.io/slate/admin.html#trigger-an-invoice-generation-for-all-parked-accounts) - The [Ruby code](https://github.com/killbill/killbill-client-ruby/blob/0c897c2006f5a8e22bbc98176e91200ff02253cd/lib/killbill_client/models/admin.rb#L35) for this endpoint does not accept the `reason`, `comment` parameters. I think this is required.
- [x] [Update the state of a paymentTransaction and associated payment](https://killbill.github.io/slate/admin.html#update-the-state-of-a-paymenttransaction-and-associated-payment) - The endpoint requires a JSON request body corresponding to the [AdminPayment](https://killbill.github.io/slate/admin.html#adminpayment-object) resource object. See `shell` code for this endpoint. However, the [Ruby code](https://github.com/killbill/killbill-client-ruby/blob/0c897c2006f5a8e22bbc98176e91200ff02253cd/lib/killbill_client/models/admin.rb#L24) does not accept a JSON body. This needs to be fixed.
- [x] [Get Queue Entries](https://killbill.github.io/slate/admin.html#get-queue-entries) endpoint accepts multiple parameters corresponding to `queueName`, `serviceName`, `withHistory`, etc. However, the [Ruby method](https://github.com/killbill/killbill-client-ruby/blob/0c897c2006f5a8e22bbc98176e91200ff02253cd/lib/killbill_client/models/admin.rb#L11) does not accept the corresponding parameters and thus needs to be updated.
- [x] [Retrieve Invoice By Id](https://killbill.github.io/slate/invoice.html#retrieve-an-invoice-by-id) - This endpoint accepts a query parameter called `withChildrenItems`. However the corresponding [Ruby method](https://github.com/killbill/killbill-client-ruby/blob/0c897c2006f5a8e22bbc98176e91200ff02253cd/lib/killbill_client/models/invoice.rb#L22) does not accept this parameter and needs to be updated.
- [x] [Retrieve Invoice By Number](https://killbill.github.io/slate/invoice.html#retrieve-an-invoice-by-number) - This endpoint accepts a query parameter called `withChildrenItems`. However the corresponding [Ruby method](https://github.com/killbill/killbill-client-ruby/blob/0c897c2006f5a8e22bbc98176e91200ff02253cd/lib/killbill_client/models/invoice.rb#L30) does not accept this parameter and needs to be updated.
- [x] - [Generate Invoice Dry Run](https://killbill.github.io/slate/invoice.html#generate-a-dry-run-invoice) - The [Ruby code](https://github.com/killbill/killbill-client-ruby/blob/0c897c2006f5a8e22bbc98176e91200ff02253cd/lib/killbill_client/models/invoice.rb#L95) for this endpoint does not accept the reason, comment parameters. I think this is required.
- [x] [Add Invoice Custom Fields](https://killbill.github.io/slate/invoice.html#add-custom-fields-to-an-invoice) - This API endpoint allows adding multiple custom fields to an invoice at once. However, the Ruby code only allows specifying a single custom field and needs to be updated
- [x] [Modify invoice custom fields](https://killbill.github.io/slate/invoice.html#modify-custom-fields-for-an-invoice) - This API endpoint allows modifying multiple custom fields at once. However, the Ruby code only allows specifying a single custom field and needs to be updated
- [x] [Delete invoice custom fields](https://killbill.github.io/slate/invoice.html#remove-custom-fields-from-invoice) - The API endpoint allows deleting multiple custom fields when multiple `customField` query parameters are specified. Refer to the **Query Parameters** section. However, the Ruby code only allows specifying a single custom field. So, the Ruby code needs to be updated so it can accept multiple `customField` values and pass these to the server side.
- [x] [Add Invoice Tags](https://killbill.github.io/slate/invoice.html#add-tags-to-invoice) - This API endpoint allows adding multiple tags to an invoice at once. However, the Ruby code only allows specifying a single tag and needs to be updated
- [x] [Delete Invoice Tags](https://killbill.github.io/slate/invoice.html#remove-tags-from-invoice) - This API endpoint allows deleting multiple tags from an invoice at once. However, the Ruby code only allows specifying a single tag and needs to be updated
- [x] Add Invoice Item Custom Fields - This API endpoint allows adding multiple custom fields to an invoice item at once. However, the Ruby code only allows specifying a single custom field and needs to be updated
- [x] Modify Invoice Item Custom Fields - This API endpoint allows modifying multiple custom fields at once. However, the Ruby code only allows specifying a single custom field and needs to be updated
- [x] Delete Invoice Item Custom Fields - The API endpoint allows deleting multiple custom fields when multiple `customField` query parameters are specified. However, the Ruby code only allows specifying a single custom field and needs to be updated.
- [x] Delete Invoice Item Tags - his API endpoint allows deleting multiple tags from an invoice item at once. However, the Ruby code only allows specifying a single tag and needs to be updated

**Comment by KBbitsP** [comment]
- [ ] [Complete existing transaction using payment external key](https://killbill.github.io/slate/payment.html#complete-an-existing-transaction-using-paymentexternalkey) - This API endpoint allows completing an existing transaction using the payment external key ( without payment ID ). However, the Ruby code errors out, though the transaction gets updated correctly. 
- [ ] [Void existing transaction using payment external key](https://killbill.github.io/slate/payment.html#void-an-existing-payment-using-paymentexternalkey ) - This API endpoint allows to void an existing transaction using the payment external key ( without payment ID ). However, the Ruby code errors out, though the transaction gets updated correctly.

**Comment by tungleduyxyz** [comment]
Hi @reshmabidikar 
The issues listed in the comment were handled here: https://github.com/killbill/killbill-client-ruby/pull/99/files
And the last one, List all custom fields is already there: https://github.com/killbill/killbill-client-ruby/blob/dd9c43306787cd63a8b7a02285d82a79fb5de4e5/lib/killbill_client/models/custom_field.rb#L14
